###

GET http://localhost:10000/getUser

###

###

POST http://localhost:10000/login HTTP/1.1
content-type: application/json
Authorization: Bearer 123124512421

{
    "username": "test",
    "password": "12345"
}
###


POST http://localhost:10000/verifyToken HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDMwMTk2ODksImlzX2F1dGhvcml6ZWQiOiJ0cnVlIiwidXNlcl9uYW1lIjoidGVzdCJ9.eP9ly48xXXE6_nTH9GSvBpL_0IEzCOLzxRSKgnCPUM8

{
    "test" : "test"
}
